server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-service}:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8070"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true 
      routes:
        # 1. AUTH SERVICE (Usa /user en el front -> /api/auth en el back)
        - id: auth-service
          uri: lb://tingesoMS-auth
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /api/auth/${segment}

        # 2. CLIENT SERVICE (Usa /client en el front -> /api/client en el back)
        - id: client-service
          uri: lb://tingesoMS-client
          predicates:
            - Path=/client/**
          filters:
            - RewritePath=/client/(?<segment>.*), /api/client/${segment}

        # 3. FEE SERVICE (Usa /fee en el front -> /api/fee en el back)
        - id: fee-service
          uri: lb://tingesoMS-fee
          predicates:
            - Path=/fee/**
          filters:
            - RewritePath=/fee/(?<segment>.*), /api/fee/${segment}

        # 4. INVENTORY SERVICE (Usa /inventory en el front -> /api/inventory en el back)
        - id: inventory-service
          uri: lb://tingesoMS-inventory
          predicates:
            - Path=/inventory/**
          filters:
            - RewritePath=/inventory/(?<segment>.*), /api/inventory/${segment}

        # 5. KARDEX SERVICE (Usa /kardex en el front -> /api/kardex en el back)
        - id: kardex-service
          uri: lb://tingesoMS-kardex
          predicates:
            - Path=/kardex/**
          filters:
            - RewritePath=/kardex/(?<segment>.*), /api/kardex/${segment}

        # 6. LOAN SERVICE (Usa /loan en el front -> /api/loan en el back)
        - id: loan-service
          uri: lb://tingesoMS-loan
          predicates:
            - Path=/loan/**
          filters:
            - RewritePath=/loan/(?<segment>.*), /api/loan/${segment}

        # 7. REPORT SERVICE (Usa /report en el front -> /api/report en el back)
        - id: report-service
          uri: lb://tingesoMS-report
          predicates:
            - Path=/report/**
          filters:
            - RewritePath=/report/(?<segment>.*), /api/report/${segment}