server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-service}:8761/eureka/
  instance:
    # Es recomendable usar el nombre del servicio o IP en lugar de localhost
    # para que Eureka sepa cómo redirigir el tráfico al gateway
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8070"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          # Esto permite que el gateway sea sensible a minúsculas/mayúsculas según el registro
          lower-case-service-id: true 
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://tingeso-auth-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /api/auth/$\{segment}
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client/**
        - id: fee-service
          uri: lb://fee-service
          predicates:
            - Path=/fee/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
        - id: kardex-service
          uri: lb://kardex-service
          predicates:
            - Path=/kardex/**
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loan/**
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/report/**