server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    # Nombre clave para que el Gateway encuentre este servicio en lb://tingesoMS_report
    name: tingesoMS_report
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/report_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-service}:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    # Facilita la comunicación interna eliminando problemas de resolución de nombres de host
    prefer-ip-address: true
