server:
  # Puerto 8080 estandarizado para el contenedor en Kubernetes
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: tingesoMS-report
  datasource:
    # Apuntamos al Service de MySQL: mysql-service
    url: jdbc:mysql://${MYSQL_HOST:mysql-service}:3306/report_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    # Usuario y contraseña inyectados desde los secretos (user_report / pass_report)
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        # Dialecto simplificado para Hibernate 6+
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-service}:8761/eureka/
  instance:
    # Identificador único para el registro en Eureka
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
