server:
  # En Kubernetes, fijar el puerto a 8080 es el estándar para facilitar el Service mapping.
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: tingesoMS_client
  datasource:
    # Cambiamos localhost por mysql-service (el nombre del Service en K8s)
    url: jdbc:mysql://${MYSQL_HOST:mysql-service}:3306/client_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    # Eliminamos el default ':root' para obligar al servicio a usar las credenciales 
    # del script de inicio (inyectadas vía Kubernetes Secrets)
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Dialecto simplificado para Hibernate 6+
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-service}:8761/eureka/
  instance:
    # ID único para evitar colisiones en Eureka
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true