server:
  # Puerto 8080 fijado para el contenedor, facilitando el Service de K8s.
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: tingesoMS-loan
  datasource:
    # Apuntamos al Service de MySQL interno: mysql-service
    url: jdbc:mysql://${MYSQL_HOST:mysql-service}:3306/loan_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    # Variables inyectadas obligatorias (sin default :root) para el usuario 'user_loan'
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        # Dialecto para Hibernate 6+ (Spring Boot 3)
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-service}:8761/eureka/
  instance:
    # Identificador único para el dashboard de Eureka
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true