server:
  # En K8s, es mejor usar un puerto fijo (8080) para el contenedor
  # y dejar que el Service de K8s haga el mapeo si es necesario.
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: tingesoMS-auth
  datasource:
    # Cambiamos localhost por mysql-service para el entorno de cluster
    url: jdbc:mysql://${MYSQL_HOST:mysql-service}:3306/auth_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # MySQLDialect detecta automáticamente la versión 8 en Hibernate 6
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-service}:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true