server:
  port: ${PORT:0}
spring:
  application:
   name: tingesoMS_report
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8761/eureka
