server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    # Vincula este microservicio con la ruta lb://tingesoMS_fee definida en el Gateway
    name: tingesoMS_fee
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/fee_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-service}:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    # Mejora la conectividad en entornos Docker/redes virtuales
    prefer-ip-address: true